#Sends a command to a roboteq motor driver, and returns the result(s)
int64 item #Roboteq information item code.
int64 index #Motor index for multi-motor setups.  Set to -1 to ignore.
int64 value #Value to write for 'set' methods.  Ignored for 'get' methods.

---

int64 response #Response code
int64 result #Result of 'get' commands.  Set to 0 for 'set' commands